"""AI-powered Jira endpoints."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException

from jira_ai.compose_issue import compose_issue_from_prompt
from jira_ai.jira_client import is_configured as jira_configured, jira_request
from jira_ai.jira_helpers import build_adf
from jira_ai.jira_users import find_user_account_id
from jira_ai.update_issue import analyze_issue_update, apply_issue_update
from schemas import AICreateIssueRequest, AIUpdateIssueRequest, IssueDraft

router = APIRouter(prefix="/ai", tags=["ai"])


def _to_list(value):
	if value is None:
		return []
	if isinstance(value, list):
		return [item.strip() for item in value if isinstance(item, str) and item.strip()]
	if isinstance(value, str):
		return [item.strip() for item in value.split(",") if item.strip()]
	return []


def _merge_draft(base: dict, draft: IssueDraft | None) -> dict:
	if not draft:
		return base
	merged = {**base}
	if draft.summary:
		merged["summary"] = draft.summary.strip()
	if isinstance(draft.description, str):
		merged["description"] = draft.description
	if draft.priority:
		merged["priority"] = draft.priority
	if draft.assignee:
		merged["assignee"] = draft.assignee
	if draft.issueType:
		merged["issueType"] = draft.issueType
	if draft.epicKey:
		merged["epicKey"] = draft.epicKey
	if draft.estimate is not None:
		merged["estimate"] = draft.estimate
	merged["labels"] = _to_list(draft.labels) or merged.get("labels") or []
	merged["components"] = _to_list(draft.components) or merged.get("components") or []
	return merged


@router.post("/create-issue")
async def ai_create_issue(payload: AICreateIssueRequest):
	if not payload.text or not payload.projectKey:
		raise HTTPException(status_code=400, detail="projectKey and text are required")

	try:
		composed = await compose_issue_from_prompt(payload.projectKey, payload.text, payload.contextText)
	except ValueError as exc:
		raise HTTPException(status_code=400, detail=str(exc)) from exc
	except Exception as exc:  # pragma: no cover - LLM/vectors may fail
		raise HTTPException(status_code=500, detail=str(exc)) from exc

	merged_generated = _merge_draft(composed["generated"], payload.draft)

	if not payload.createOnJira:
		return {
			"mode": "compose",
			"projectKey": composed["projectKey"],
			"generated": merged_generated,
			"context": {"ragChunks": composed.get("ragChunks")},
		}

	if not jira_configured():
		raise HTTPException(status_code=501, detail="Jira credentials are not configured")

	issue_body = {
		"fields": {
			"project": {"key": composed["projectKey"]},
			"summary": merged_generated.get("summary") or "Draft from AI assistant",
			"description": build_adf(
				merged_generated.get("description") or "Generated by Jira AI assistant"
			),
			"issuetype": {"name": merged_generated.get("issueType") or "Task"},
			"labels": merged_generated.get("labels") or [],
		}
	}

	if merged_generated.get("priority"):
		issue_body["fields"]["priority"] = {"name": merged_generated["priority"]}
	components = merged_generated.get("components") or []
	if components:
		issue_body["fields"]["components"] = [{"name": name} for name in components]

	if merged_generated.get("assignee"):
		account_id = await find_user_account_id(merged_generated["assignee"])
		if account_id:
			issue_body["fields"]["assignee"] = {"accountId": account_id}

	try:
		created = await jira_request("/rest/api/3/issue", "POST", issue_body)
	except Exception as exc:  # pragma: no cover - network errors
		raise HTTPException(status_code=502, detail=str(exc)) from exc

	return {
		"mode": "compose",
		"projectKey": composed["projectKey"],
		"generated": merged_generated,
		"created": created,
	}


@router.post("/update-issue")
async def ai_update_issue(payload: AIUpdateIssueRequest):
	if not payload.text:
		raise HTTPException(status_code=400, detail="text is required")

	try:
		analysis = await analyze_issue_update(payload.text)
		result = await apply_issue_update(analysis, source_text=payload.text)
	except ValueError as exc:
		raise HTTPException(status_code=400, detail=str(exc)) from exc
	except RuntimeError as exc:
		raise HTTPException(status_code=502, detail=str(exc)) from exc
	except Exception as exc:
		raise HTTPException(status_code=500, detail=str(exc)) from exc

	return {**result, "analysis": analysis}


__all__ = ["router"]
