const baseShadow = "0 18px 36px rgba(15, 29, 61, 0.12)";
const subtleBorder = "1px solid #d8deeb";

const styles = {
  page: {
    minHeight: "100vh",
    background: "#eef2f8",
    padding: "3rem 0",
  },
  container: {
    width: "min(1080px, 92vw)",
    margin: "0 auto",
    display: "grid",
    gap: "2.5rem",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  hero: {
    display: "grid",
    gap: "0.75rem",
  },
  title: {
    margin: 0,
    fontSize: "2.5rem",
    lineHeight: 1.2,
    color: "#0f1d3d",
  },
  subtitle: {
    margin: 0,
    color: "#4a5878",
    fontSize: "1rem",
    lineHeight: 1.6,
  },
  controlsCard: {
    background: "#fff",
    borderRadius: 18,
    padding: "1.75rem",
    boxShadow: baseShadow,
    display: "grid",
    gap: "1.25rem",
  },
  panel: {
    background: "#fff",
    borderRadius: 18,
    padding: "1.75rem",
    boxShadow: baseShadow,
    display: "grid",
    gap: "1.25rem",
  },
  controlsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "1.25rem",
  },
  controlGroup: {
    display: "grid",
    gap: "0.5rem",
  },
  templateRow: {
    display: "grid",
    gap: "0.5rem",
  },
  filenameRow: {
    display: "grid",
    gap: "0.75rem",
  },
  label: {
    fontWeight: 600,
    color: "#0f1d3d",
    fontSize: "0.95rem",
  },
  input: {
    border: subtleBorder,
    borderRadius: 10,
    padding: "0.65rem 0.85rem",
    fontSize: "0.95rem",
    background: "#fdfefe",
  },
  sectionList: {
    display: "grid",
    gap: "1.75rem",
  },
  sectionCard: {
    background: "#fff",
    borderRadius: 20,
    padding: "1.75rem",
    boxShadow: baseShadow,
    display: "grid",
    gap: "1.25rem",
  },
  section: {
    background: "#fff",
    borderRadius: 20,
    padding: "1.75rem",
    boxShadow: baseShadow,
    display: "grid",
    gap: "1.25rem",
  },
  sectionHeader: {
    display: "flex",
    gap: "1rem",
    alignItems: "flex-start",
  },
  sectionBadge: {
    minWidth: 36,
    height: 36,
    borderRadius: 999,
    background: "#1c3f91",
    color: "#fff",
    fontWeight: 600,
    fontSize: "0.95rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "0.1rem",
  },
  sectionHeading: {
    display: "grid",
    gap: "0.35rem",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "1.35rem",
    color: "#0f1d3d",
  },
  sectionDescription: {
    margin: 0,
    color: "#4a5878",
    fontSize: "0.95rem",
    lineHeight: 1.5,
  },
  sectionBody: {
    display: "grid",
    gap: "1.25rem",
  },
  fieldBlock: {
    display: "grid",
    gap: "0.65rem",
    background: "#f7f9fc",
    border: subtleBorder,
    borderRadius: 14,
    padding: "1rem 1.25rem",
  },
  textarea: {
    border: "1px solid #c6d2eb",
    borderRadius: 10,
    padding: "0.85rem",
    minHeight: 140,
    fontSize: "0.95rem",
    lineHeight: 1.5,
    background: "#fff",
    resize: "vertical",
  },
  helpText: {
    margin: 0,
    fontSize: "0.85rem",
    color: "#5a678a",
    lineHeight: 1.4,
  },
  checkboxRow: {
    border: subtleBorder,
    borderRadius: 12,
    padding: "0.85rem 1rem",
    background: "#fff",
    display: "grid",
    gap: "0.5rem",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontWeight: 500,
    color: "#0f1d3d",
  },
  checkboxText: {
    fontSize: "0.95rem",
  },
  inlineActions: {
    display: "flex",
    gap: "0.5rem",
  },
  tableWrapper: {
    overflowX: "auto",
    borderRadius: 12,
    border: subtleBorder,
    background: "#fff",
  },
  dataTable: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
  },
  tableCell: {
    borderBottom: subtleBorder,
    borderRight: subtleBorder,
    padding: "0.45rem 0.35rem",
    verticalAlign: "top",
    background: "#fdfefe",
  },
  tableCellTextarea: {
    width: "100%",
    minHeight: 64,
    border: "1px solid #c6d2eb",
    borderRadius: 8,
    padding: "0.55rem",
    fontSize: "0.9rem",
    resize: "vertical",
  },
  tableRowActions: {
    minWidth: 100,
    textAlign: "center",
    background: "#f2f5fb",
    borderLeft: subtleBorder,
  },
  addRowBtn: {
    marginTop: "0.75rem",
    padding: "0.5rem 1rem",
    borderRadius: 999,
    border: "none",
    background: "linear-gradient(135deg, #dbe4ff, #b7ccff)",
    color: "#1c3f91",
    cursor: "pointer",
    fontSize: "0.85rem",
    fontWeight: 600,
    alignSelf: "flex-start",
  },
  removeRowBtn: {
    padding: "0.35rem 0.75rem",
    borderRadius: 999,
    border: "none",
    background: "#ffecec",
    color: "#b42318",
    cursor: "pointer",
    fontSize: "0.8rem",
    fontWeight: 600,
  },
  polishBtn: {
    alignSelf: "flex-start",
    padding: "0.4rem 0.75rem",
    borderRadius: 999,
    border: "none",
    background: "#e8edff",
    color: "#1c3f91",
    cursor: "pointer",
    fontSize: "0.85rem",
    fontWeight: 600,
  },
  addBtn: {
    alignSelf: "flex-start",
    padding: "0.35rem 0.65rem",
    borderRadius: 5,
    border: "1px solid #2c7a7b",
    background: "#f0fdfa",
    color: "#285e61",
    cursor: "pointer",
    fontSize: "0.85rem",
  },
  removeBtn: {
    padding: "0.35rem 0.65rem",
    borderRadius: 5,
    border: "1px solid #c53030",
    background: "#fff5f5",
    color: "#9b2c2c",
    cursor: "pointer",
    fontSize: "0.85rem",
  },
  inlineNote: {
    fontSize: "0.9rem",
    color: "#516087",
  },
  generateBar: {
    display: "flex",
    justifyContent: "flex-end",
  },
  generateBtn: {
    padding: "0.95rem 1.9rem",
    borderRadius: 999,
    border: "none",
    background: "linear-gradient(135deg, #1c3f91, #3455d1)",
    color: "#fff",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 14px 30px rgba(28, 63, 145, 0.2)",
  },
  error: {
    background: "#fff5f5",
    color: "#b42318",
    padding: "0.9rem 1.1rem",
    borderRadius: 12,
    border: "1px solid #f8c1c1",
  },
  callout: {
    background: "#f7f9ff",
    border: "1px solid #d4dcff",
    borderRadius: 12,
    padding: "1rem 1.25rem",
    color: "#3b4a72",
    fontSize: "0.95rem",
    lineHeight: 1.5,
  },
  polishOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    background: "rgba(14, 22, 44, 0.45)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backdropFilter: "blur(3px)",
  },
  polishModal: {
    background: "#fff",
    padding: "1.75rem",
    borderRadius: 16,
    maxWidth: 540,
    width: "100%",
    maxHeight: "80vh",
    overflowY: "auto",
    boxShadow: "0 24px 48px rgba(15, 29, 61, 0.22)",
    display: "grid",
    gap: "0.75rem",
  },
  modalTitle: {
    margin: 0,
    color: "#0f1d3d",
  },
  polishOption: {
    border: "1px solid #d3daf5",
    borderRadius: 12,
    padding: "0.85rem",
    cursor: "pointer",
    whiteSpace: "pre-wrap",
    lineHeight: 1.5,
  },
  closeModalBtn: {
    marginTop: "0.5rem",
    padding: "0.5rem 0.9rem",
    borderRadius: 999,
    border: "none",
    background: "#0f1d3d",
    color: "#fff",
    cursor: "pointer",
    fontWeight: 600,
  },
};

export default styles;
